// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://odjhezcreepbkqmagypv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9kamhlemNyZWVwYmtxbWFneXB2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU5ODY1NjMsImV4cCI6MjA2MTU2MjU2M30.FMWxFMcBsBKFPpCatdYXq0v4lZezFWcycqzuN5SyfTU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);